
# ?? Actuator ??? Web?? ?????.
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
        # exclude ? ???? ? ????? ?? ?? ?????? ????.
# Shutdown ??? ?????. POST ? ???? ??.
# ??? ???? ???? ??.
#  endpoint:
#    shutdown:
#      enabled: true

#?? ??? ??? ??????? ??? ??? ? ? ??? ???? ?? ??? ???????
#???? ??????? ?????, ??? ????? ??? ??? ?? ??? ???? ????
#????? => /actuator/health
management:
  # info, os?? ?????? ??? ??? ??.
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
# ?? ??? ??? ????
  # ?? ??? Security? ?????, ??? ??.
# ????? ????? ????
  server:
    port: 9292
  endpoint:
    health:
      # ?? ???? ??? ??????
      # show-components? ??
#      show-details: always
      show-components: always

  endpoints:
    web:
      exposure:
        include: "*"

# env ??? ??????? ??? ??
# info: ? ??? ???????.
info:
  app:
    name: hello-actuator
    company: yh

# ?? ??? ??? ? ??.
logging:
  level:
    # ?? ???? ????.
    hello.controller: debug

#{
# "status": "UP",
# "components": {
# "db": {
# "status": "UP",
# "details": {
# "database": "H2",
# "validationQuery": "isValid()"
# }
# },
# "diskSpace": {
# "status": "UP",
# "details": {
# "total": 994662584320,
# "free": 303418753024,
# "threshold": 10485760,
# "path": ".../spring-boot/actuator/actuator/.",
# "exists": true
# }
# },
# "ping": {
# "status": "UP"
# }
# }
#}


