
# ?? Actuator ??? Web?? ?????.
management:
  endpoints:
    web:
      exposure:
        include: "*"
        # exclude ? ???? ? ????? ?? ?? ?????? ????.
# Shutdown ??? ?????. POST ? ???? ??.
# ??? ???? ???? ??.
  endpoint:
    shutdown:
      enabled: true
