
# ?? Actuator ??? Web?? ?????.
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
        # exclude ? ???? ? ????? ?? ?? ?????? ????.
# Shutdown ??? ?????. POST ? ???? ??.
# ??? ???? ???? ??.
#  endpoint:
#    shutdown:
#      enabled: true

#?? ??? ??? ??????? ??? ??? ? ? ??? ???? ?? ??? ???????
#???? ??????? ?????, ??? ????? ??? ??? ?? ??? ???? ????
#????? => /actuator/health
management:
  endpoint:
    health:
      # ?? ???? ??? ??????
      # show-component? ??
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#{
# "status": "UP",
# "components": {
# "db": {
# "status": "UP",
# "details": {
# "database": "H2",
# "validationQuery": "isValid()"
# }
# },
# "diskSpace": {
# "status": "UP",
# "details": {
# "total": 994662584320,
# "free": 303418753024,
# "threshold": 10485760,
# "path": ".../spring-boot/actuator/actuator/.",
# "exists": true
# }
# },
# "ping": {
# "status": "UP"
# }
# }
#}


