-- 조건에 부합하는 중고거래 댓글 조회하기
-- 제 1답안

SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, 
DATE_format(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE 
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID
WHERE DATE_format(b.CREATED_DATE, '%Y-%m-%d') >= '2022-10-01' AND DATE_format(b.CREATED_DATE, '%Y-%m-%d') < '2022-11-01'
ORDER BY r.CREATED_DATE, b.TITLE

-- 제 2답안

SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, 
DATE_format(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE 
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID
WHERE DATE_format(b.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY r.CREATED_DATE, b.TITLE
